import { useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [counter, setCounter] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js Hello World!
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <div class="bg-slate-100 rounded-xl p-8 dark:bg-slate-800">
            <h1 className="text-8xl text-center">{counter}</h1>
            <button
              class="h-10 px-6 mx-4 font-semibold rounded-md bg-black text-white"
              onClick={ () => setCounter(counter - 1) }
            >
              -
            </button>
            <button
              class="h-10 px-6 mx-4 font-semibold rounded-md bg-black text-white"
              onClick={ () => setCounter(counter + 1) }
            >
              +
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
