import { useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery } from "react-query";
import axios from "axios";

export default function Home() {
  const [winner, setWinner] = useState(null);

  const { data: pokemon, isLoading, refetch } = useQuery(["pokemon"],async () => {
    const pokeRes = await axios.get("https://pokeapi.co/api/v2/pokemon?limit=100");
    const fRnd = Math.floor(Math.random() * 100);
    const first = await axios.get(pokeRes.data.results[fRnd].url);
    const sRnd = Math.floor(Math.random() * 100);
    const second = await axios.get(pokeRes.data.results[sRnd].url);

    return [first.data, second.data];
  }, {
    initialData: []
  });

  const battle = () => Math.random() >= .5 ? setWinner(1) : setWinner(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-7xl mb-12">Welcome to Pekemon Battle!</h1>

        <div className="flex flex-col  bg-slate-100 rounded-xl p-8 dark:bg-slate-800">
          <div className="flex flex-row  bg-slate-100 rounded-xl p-8 dark:bg-slate-800">
            <div className="w-2/5">
              {winner === 0 && <h1 className="text-6xl text-green-700 text-center">WINNER!</h1>}
              <img src={pokemon[0]?.sprites.front_default} className="w-96" />
              <h1 className="text-6xl text-center">{pokemon[0]?.name}</h1>
            </div>

            <div className="flex justify-center items-center w-1/5">
              <h1 className="text-8xl text-center">VS</h1>
            </div>

            <div className="w-2/5">
              {winner === 1 && <h1 className="text-6xl text-green-700 text-center">WINNER!</h1>}
              <img src={pokemon[1]?.sprites.front_default} className="w-96" />
              <h1 className="text-6xl text-center">{pokemon[1]?.name}</h1>
            </div>
          </div>

          <div className="flex flex-row justify-center  bg-slate-100 rounded-xl p-8 dark:bg-slate-800">
            <button
              className="mx-4 font-semibold rounded-md bg-black text-white capitalize text-2xl p-6"
              onClick={() => {
                setWinner(null);
                refetch();
              }}
            >
              rematch
            </button>
            <button
              className="mx-4 font-semibold rounded-md bg-black text-white capitalize text-2xl p-6"
              onClick={battle}
            >
              battle
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
